name: Build and Test API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -la

      - name: Build Docker Image
        run: docker build -t hehe .
