name: Build and Test API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Adding Bandit Scanner
        uses: DevSecNinja/python-bandit-scan@v1
        with:
          path: 'Project'
          exit_zero: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build Docker Image
        run: |
          cd Project
          docker build -t hehe .
      
